### ISSUE TITLE
RIAA: I will stop downloading from youtube once it is offline :)

### ISSUE THREAD

**Issue by alexruedi** [lrvick/youtube-dl#1]
## Checklist

- [ ] I'm asking a question
- [ ] I've looked through the README and FAQ for similar questions
- [ ] I've searched the bugtracker for similar questions including closed ones

## Question

WRITE QUESTION HERE

**Comment by alexruedi** [comment]
well done :) seems offline now

**Comment by floydssoda** [comment]
Blink twice if you were threatened.
