### ISSUE TITLE
Web archive youtube-dl

### ISSUE THREAD

**Issue by iamgmujtaba** [lrvick/youtube-dl#2]
If someone interested in issues thread of original youtube-dl

- Web archive: https://web.archive.org/web/20201019090822/https://github.com/ytdl-org/youtube-dl

**Comment by GhbSmwc** [comment]
![image](https://user-images.githubusercontent.com/13095760/98452429-4af0df00-211d-11eb-8109-df16dd0ce4b1.png)

**Comment by floydssoda** [comment]
That makes me WANT to steal!
